SET IDENTITY_INSERT dbo.Land ON

insert Into dbo.Land(LandID,Beschrijving)
values
(1, 'België'),
(2, 'Verenigde Staten'),
(3, 'Sovjet-Unie'),
(4, 'Frankrijk'),
(5, 'Duitsland'),
(6, 'Nederland'),
(7, 'Spanje'),
(8, 'Italië'),
(9, 'Rusland'),
(10, 'Wit-Rusland'),
(11, 'China'),
(12, 'Japan'),
(13, 'Australië'),
(14, 'Turkijë'),
(15, 'Griekenland'),
(16, 'Tsjecho-Slowakije'),
(17, 'Tsjechië'),
(18, 'Slowakije'),
(19, 'Hongarije'),
(20, 'Oekraïne'),
(21, 'Verenigd Koninkrijk'),
(22, 'Ierland'),
(23, 'Canada'),
(24, 'Mexico'),
(25, 'Brazilië'),
(26, 'Argentinië'),
(27, 'Chili'),
(28, 'Zuid-Afrika'),
(29, 'Marokko'),
(30, 'Algerije'),
(31, 'Egypte'),
(32, 'Congo'),
(33, 'Denenmarken'),
(34, 'Noorwegen'),
(35, 'Zweden'),
(36, 'Finland'),
(37, 'Ijsland'),
(38, 'Luxemburg'),
(39, 'Zwitserland'),
(40, 'Oostenrijk'),
(41, 'Joegoslavië'),
(42, 'Verenigde Arabische Emiraten'),
(43, 'Saoedi-Arabië'),
(44, 'Israel'),
(45, 'Vietnam'),
(46, 'Thailand'),
(47, 'Noord-Korea'),
(48, 'Zuid-Korea'),
(49, 'Portugal'),
(50, 'Overig');